### ISSUE TITLE
"Runme: Add Runme to recommended extensions" fails on Linux

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#1170]
Likely related to not accounting for fs/path platform specifics. VS Code should have primitives to deal with those.

E.g. on extension `v3.1.2` and `vscode@v1.86.0` on `ubuntu-22.04` on `x86_64`:

![Image](https://github.com/stateful/vscode-runme/assets/250527/7569cb0c-66c5-441e-a1b5-a5ddc3db995a)

**Comment by pastuxso** [comment]
@sourishkrout could you please include the source of the installation?

It could be a Snap, Deb package, or a different source.

**Comment by sourishkrout** [comment]
I believe it's whatever's bundled with the extension, since this is an
extension feature.

**Comment by sourishkrout** [comment]
Fixed and merged @degrammer?

**Comment by sourishkrout** [comment]
This was a `json` vs `jsonc` problem.
