### ISSUE TITLE
How to opt out of Runme Cloud

### ISSUE THREAD

**Issue by mt-ronkorving** [stateful/vscode-runme#1246]
I've been experimenting with Runme in VS Code, and I really love the set of capabilities.

But I'm a bit puzzled how and why it's uploading command output to Runme Cloud. At this time, I'm happy for output to just go straight to my disk. More importantly, I have not been able to find an option anywhere to opt out of my command output being uploaded to Runme Cloud. I'm sure I'm just missing something.

Could someone advise?

Thank you.

**Comment by sourishkrout** [comment]
Hi @mt-ronkorving, thanks for filing the ticket!

In the most recent release, to disable the login prompt you can toggle following setting (`runme.app.loginPrompt`):
![image](https://github.com/stateful/vscode-runme/assets/250527/9487025e-e2e9-4e3c-bd3f-a6dcd592d175)

This will prevent the prompt from reoccurring. Btw, we are only a few days out from releasing a reworked Runme version where local-mode for Auto-Save is the only option which should solve the problem described altogether.

Please let me know if this helps, @mt-ronkorving.

**Comment by mt-ronkorving** [comment]
Thank you, that worked! 🙇
