### ISSUE TITLE
Cell IDs are still injected when setting Lifecycle Identity to None

### ISSUE THREAD

**Issue by mt-ronkorving** [stateful/vscode-runme#1251]
In my settings:

<img width="691" alt="image" src="https://github.com/stateful/vscode-runme/assets/38023285/066ecd2f-f4c7-4672-8ca9-37e0c384e309">

But when I open and run some cells in my runbook, it still injects `{"id":"etc"}` into my runbook.
It does not however (as expected) inject a Runme header at the top of the file. So the option seems to half work.

I restarted VS Code, and can confirm the setting persisted, but the result is as described.

**Comment by mt-ronkorving** [comment]
I also noticed that when I remove the Runme header, it prevents the runbook output from being saved locally.

**Comment by sourishkrout** [comment]
Thanks for reporting the issue @mt-ronkorving. Taking a look into this today. It should not write any IDs, not even cells when set to `None`.

Currently writing the runbook output requires the document-level lifecycle ID. From what I'm gathering you would like this feature to work even if lifecycle identity is set to `None`? I believe we should be able to "fix" that. Can confirm, please, @mt-ronkorving? I can spin off a separate ticket for it.

**Comment by sourishkrout** [comment]
@mt-ronkorving we just shipped `v3.3.1712245402` into `pre-release` which you can test drive this way:

<img width="1063" alt="image" src="https://github.com/stateful/vscode-runme/assets/250527/16efc9b8-ac5b-43ea-9278-9a859af7bc10">

The fix will likely go into `v3.3.2` (stable) in the next few days. Also, we tweaked our integration test suite which had a blind spot for turning off lifecycle identity. Sorry about that!

Also spun off https://github.com/stateful/vscode-runme/issues/1255 as a separate issue.

**Comment by mt-ronkorving** [comment]
Thanks so much :) I'll be following #1255 👍

**Comment by mt-ronkorving** [comment]
No worries, I'm not blocked 👍 
Thanks for caring :)

**Comment by sourishkrout** [comment]
> No worries, I'm not blocked 👍 Thanks for caring :)

Of course! Closing this issue as solved.
