### ISSUE TITLE
Annotations UI Improvements

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#131]
The current annotations UI needs improvements, review the layout display (probably a vertical one) since the current distribution may need more screen real state, it can easily run out of space for certain screens or even when zooming.

![Image](https://user-images.githubusercontent.com/4001529/213330107-e2bec4c3-e0a4-41c5-8f92-76ef0b87a047.png)

**Comment by christian-bromann** [comment]
To re-iterate some comments I made before in other threads:
- I would merge the inputs for mime type and name to be a single input element which value is omitted if empty
- as mentioned in #116 the current solution to integrate these inputs right below the code block limits the amount of screen real estate we can use, it works with the current 5 inputs but will get out of hand when that increases, I personally still feel that a sidebar provides us more options

**Comment by sourishkrout** [comment]
As discussed, we want to make a best effort iteration of the UI that's there. This feature will ship tomorrow. As per discussion on the closed sidebar approach PR (https://github.com/stateful/vscode-runme/pull/115), it's been decided to move ahead.

@degrammer one thing that's somewhat important to me is to have a "?" on every annotation that ideally shows a short description of its effect on the cell execution.

**Comment by degrammer** [comment]
Working on the "?" progress for the enhancements here https://github.com/stateful/vscode-runme/pull/134

**Comment by sourishkrout** [comment]
Done.
