### ISSUE TITLE
Handle ENV VAR interpolation as part of cloud renderers

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#1351]
1. Handle simple interpolation with ENV vars in:

`https://console.cloud.google.com/kubernetes/list/overview?project=$PROJECT_ID`

Where PROJECT_ID should be resolved from the environment.

2. Account for scenarios that are actually valid bash, e.g. `open https://github.com/stateful/vscode-runme `

3. Once done, update the cloud renderer examples.

**Comment by sourishkrout** [comment]
Implemented as part of https://github.com/stateful/vscode-runme/pull/1369 and released since.
