### ISSUE TITLE
Runme notebooks panel: refresh tree

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#158]
Let's add a simple refresh button or, alternatively, a file watcher could be used to trigger infrequent refreshes.

![image](https://user-images.githubusercontent.com/250527/214868017-1e8640e8-7d44-4d87-be13-59d50d5d8a22.png)

**Comment by christian-bromann** [comment]
Implemented in https://github.com/stateful/vscode-runme/pull/283
