### ISSUE TITLE
Node 20 Support

### ISSUE THREAD

**Issue by pastuxso** [stateful/vscode-runme#1580]
Recently, I noticed how our dependency modules are moving to Node 20. For example: https://github.com/microsoft/vscode-vsce/pull/1035 https://github.com/stateful/vscode-runme/pull/1567

Right now, the unique blocker is the usage of the **--experimental-specifier-resolution=node**, which starting from Node v19 has been deprecated. To replace it requires the usage of loaders like https://github.com/barhun/extensionless, which enables support to import modules without the file extension. In our case, modules from [Buf](https://buf.build/) are using relative imports without file extensions.

**Comment by sourishkrout** [comment]
More importantly we should probably track with VS Code's Electron/Node version:

```
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```
