### ISSUE TITLE
The CLI command disappeared from the VSCode plugin

### ISSUE THREAD

**Issue by forseti** [stateful/vscode-runme#1692]
Hi Team,

I noticed that the `CLI` command has disappeared  in the newer VSCode and CodeServer plugins. Instead I can see the new Fork command that does not seem to run the Cell command in the terminal.

![runme](https://github.com/user-attachments/assets/ae4f3aa7-0a92-4254-b462-d65ba0120593)

It seems to be disabled in favor of the `Fork` command. 
https://github.com/stateful/vscode-runme/blob/0b81a900873c71fdc66d300f3396a714a21e48ef/src/extension/provider/cellStatusBar/notebook.ts#L29

```javascript
    // todo(sebastian): disable for Fork; retire it?
    // this.#cellStatusBarItems.add(new CLIStatusBarItem(this.kernel))
    this.#cellStatusBarItems.add(new ForkStatusBarItem(this.kernel))
```

Are they supposed to be doing the same thing? If not, could We have the `CLI` back? 
I find that the `CLI` is very useful when I need to selectively copy/paste the output. It is not possible to do it with the Cell output.

Thanks!

**Comment by sourishkrout** [comment]
Thanks for filing this issue. We did indeed remove the `CLI` button in favor of `Fork`. They don't exactly work the same way, though. Sorry about breaking your workflow.

We'll return a separate `CLI` button in the next few days. Just to clarify you can't select anything in the Cell Output? What platform are running on?

**Comment by forseti** [comment]
Hi @sourishkrout 

> Thanks for filing this issue. We did indeed remove the CLI button in favor of Fork. They don't exactly work the same way, though. Sorry about breaking your workflow.

Thanks. And sorry for the trouble too.

> We'll return a separate CLI button in the next few days. Just to clarify you can't select anything in the Cell Output? What platform are running on?

I can select the content of Cell Output, but it doesn't allow me to selectively copy them using CTRL+C:
![image](https://github.com/user-attachments/assets/9d645940-76fb-40e1-9d27-0b626dfd3bb4)

Nor does it allow me to use `Copy Cell Output` to copy the selected parts:
![image](https://github.com/user-attachments/assets/8d23a28f-786e-456b-9d04-47b7bccf5d5f)

If this selective copy can work, I'm happy to part with the CLI button.

Thanks again!

**Comment by sourishkrout** [comment]
> > What platform are running on?
> 
> It's on Ubuntu.
> 
> Thanks again!

Thank you. We've reproduced the issue on Linux, and @pastuxso is looking into fixing it. Independently, we'll bring back the CLI button, anyways.

**Comment by forseti** [comment]
Hi Team,
I can see the `CLI` button is enabled now. 
Thanks Team :pray:

**Comment by sourishkrout** [comment]
@forseti that's great. Can you also confirm that `CTRL+SHIFT+C` will now copy the terminal output on Linux please?

**Comment by sourishkrout** [comment]
> @forseti that's great. Can you also confirm that `CTRL+SHIFT+C` will now copy the terminal output on Linux, please?

Never mind. Just saw your comments on the PR.
