### ISSUE TITLE
Failed parsing when curl is used with parameters in URL

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#181]
The following runme block fails:

    ```sh
    curl https://api.github.com/search/repositories?q=node+in:name+language:javascript&sort=stars&order=desc
    ```

due to:

```
zsh:1: parse error near `&'
failed to run command "set -e -o pipefail;curl https://api.github.com/search/repositories?q=node+in:name+language:javascript&sort=stars&order=desc;\n": exit status 1
```

Not sure why and if this will be fixed once we switch over to the runme execution engine.

**Comment by joseeantonior** [comment]
I have confirmed that this is no longer an issue. Also, in bash, the `&` character is used to put a task in the background, which is why this would require quotes around the URL in order to be properly executed. All of this is pointing to expected behavior as of today.
