### ISSUE TITLE
Extension Does Not Work on Windows

### ISSUE THREAD

**Issue by manuth** [stateful/vscode-runme#20]
Currently, this extension does not work on systems running windows.

Following error is reported in vscode's output panel:
```
[exthost] [error] Error: ENOENT: no such file or directory, open '/c:/Users/Manuel/.vscode-oss/extensions/stateful.runme-0.2.8-universal/wasm/runme.wasm'
	at Object.openSync (node:fs:585:3)
	at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
	at Object.readFileSync (node:fs:453:35)
	at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
	at new t.Serializer (c:\Users\Manuel\.vscode-oss\extensions\stateful.runme-0.2.8-universal\out\extension.js:2:619310)
	at t.activate (c:\Users\Manuel\.vscode-oss\extensions\stateful.runme-0.2.8-universal\out\extension.js:2:613674)
	at Fn._callActivateOptional (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:17678)
	at Fn._callActivate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:17338)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:8191)
	at async E._waitForDepsThenActivate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:8133)
	at async E._initialize (c:\Program Files\VSCodium\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:7497)
```

I assume the error is caused by this statement here:
https://github.com/stateful/vscode-runme/blob/ed14392e54a3234a392d5a758dbb39b5c88a6bbe/src/extension/notebook.ts#L26

Here, `path` is used where actually `fsPath` is supposed to be used.
According to the [VS Code API](https://code.visualstudio.com/api/references/vscode-api#Uri), `path` returns the path segment of an URI while `fsPath` returns the corresponding file system path.

While this does not make a difference, really, for unix systems, for windows, it causes the code to not work.

Thanks for this great extension anyhow - can't wait to see it working on my system :smile:

**Comment by sourishkrout** [comment]
Thanks for reporting this @manuth. I can make the fix to move from `path` to `fsPath` today, we haven't done a whole lot of Windows testing yet but I'd love to make progress here. Stay tuned! I'll ping you (complete this issue) when we have this simple change made and tested 👍 .

**Comment by manuth** [comment]
Awesome! Thank you so much for your rapid answer 😄

**Comment by sourishkrout** [comment]
Thank you for getting involved. Just released `v0.2.11` which will usually be distributed to VS Code via the marketplace in like 20-30min. It'll use `fsPath` everywhere now. The vsix binary is also available here https://github.com/stateful/vscode-runme/releases/tag/0.2.11 if you want to install it directly.

Definitely open more tickets if you wind up running into more issues.

https://github.com/stateful/vscode-runme/commit/f6298eee3a8485b31b2d0d0aa2cdad71d347e741

**Comment by manuth** [comment]
Great 😄 
Works out quite well. Windows complains about the `set -e` statement as such a command does not exist. However, it does not prevent the other commands from executing, so it's fine for now, I guess.

Thanks for the great work 😄

**Comment by sourishkrout** [comment]
> Great 😄 Works out quite well. Windows complains about the `set -e` statement as such a command does not exist. However, it does not prevent the other commands from executing, so it's fine for now, I guess.
> 
> Thanks for the great work 😄

Sweet! We structured the shell settings code to be platform-specific already. I'll make another release in the coming days that just makes it empty for Windows.

You can track progress here: https://github.com/stateful/vscode-runme/issues/21

**Comment by manuth** [comment]
@sourishkrout Are you planning to release the new updated version to open-vsx as well?
That woulod be awesome 😄

**Comment by sourishkrout** [comment]
> @sourishkrout Are you planning to release the new updated version to open-vsx as well? That woulod be awesome 😄

Yes, absolutely. Publishing didn't work yesterday (assuming the registry was down?). I will try again today.

You on VSCodium, @manuth or something else?

**Comment by manuth** [comment]
I'm using VSCodium as often as I can, though there are some cases where I have to rely on VSCode like, for example, when working on remote environments (using devcontainers, ssh etc.) or when working with Python (bc "Pylance" is not available on open-vsx). But other than that, all technologies work great on Codium
