### ISSUE TITLE
Unit test code cells always being assigned UUIDs

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#203]
This is relevant for adding code cells from the UI as well as deserialization.

Let's make sure we have sufficient test coverage.

Follow up to https://github.com/stateful/vscode-runme/pull/201.

**Comment by christian-bromann** [comment]
@sourishkrout do you think we can close this, given #475 was merged?

**Comment by sourishkrout** [comment]
yes, go for it please
