### ISSUE TITLE
Bring up `runme server` inside of the extension

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#204]
As part of shifting towards the GRPC-interface for both execution and parser, we need to bring up `runme server --address localhost:8080` we can hardcode the port for now but probably want to start assigning it dynamically.

The `runme` CLI binary will be distributed as part of the extension (not part of this effort; handled independently). For now we can just assume the `runme` binary is in the PATH (please install as per instructions https://github.com/stateful/runme/releases).

Check points:
- [x] Ensure the process that starts the server is always up, implement a retry mechanism in case of failure, if the retry fails, display an error message to the user
- [x] In case of failure, figure out sending anonymized  telemetry data 
- [x] Ensure the process survives VS Code window reloading

**Comment by degrammer** [comment]
Requires additional work tracked under https://github.com/stateful/vscode-runme/issues/224 and https://github.com/stateful/vscode-runme/issues/225
