### ISSUE TITLE
Annotations sometimes broken: wrong `NotebookCellKind`

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#206]
![2023-02-14 16-15-21](https://user-images.githubusercontent.com/16108792/218876847-7c718ef6-59e3-4dc0-9b65-18a53f812984.gif)

~Upon inspection by the debugger, the `NotebookCellKind` of the cell has been incorrectly set to `Markup`, so the UUID is never generated, and even if it was, it won't get past the newly added check in `kernel` as per sebastian's changes in #201.~

EDIT: this is wrong, see below comment

Not sure if this is a regression or an existing issue, and also not sure what triggers it because in some notebooks its fine. @sourishkrout lmk if you have some idea why this is happening.

**Comment by sourishkrout** [comment]
There's a chance that the `onChange` won't fire in time. But that's just a wild guess. Maybe we should just introduce an actual `Save` button. Let's do some digging first though.

**Comment by sourishkrout** [comment]
> @sourishkrout Haha, this is because you used `break` instead of `continue`:
> 
> ```ts
>           if (
>             cell.kind !== NotebookCellKind.Code ||
>             cell.document.uri.fsPath !== editor.notebook.uri.fsPath) {
>             break
>           }
> 
>           if (cell.metadata?.['runme.dev/uuid'] === undefined) {
>             console.error(`[Runme] Cell with index ${cell.index} lacks uuid`)
>             break
>           }
> ```
> 
> See, if there's a non-code block before a code block, it'll break from the loop pre-maturely. I'll make a PR :p

🤦

**Comment by sourishkrout** [comment]
Not my greatest work
