### ISSUE TITLE
Improve UX for languages without executor

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#22]
We currently silently fail when a code block is non-shell-ish. We could either display a warning message that the language is not yet support or stop short of rendering a code block as cell in the first place.

There might even be other, better, options.

**Comment by christian-bromann** [comment]
What do you think about: https://github.com/stateful/vscode-runme/pull/35

**Comment by sourishkrout** [comment]
> What do you think about: #35

Fixed in referenced PR.
