### ISSUE TITLE
Validation hiccup with comma in annotations metadata

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#223]
The last example in https://raw.githubusercontent.com/stateful/vscode-runme/main/examples/README.md has a comma in between annotations which is being parsed as `false,`. This will trip up the validation logic. We should trim stop characters as part of preprocessing.

We should also create a follow up ticket to consider removing the comma in the underlying parser (https://github.com/stateful/runme).

**Comment by degrammer** [comment]
Fixed here https://github.com/stateful/vscode-runme/pull/227
