### ISSUE TITLE
Feature request: Add codelens support

### ISSUE THREAD

**Issue by pomdtr** [stateful/vscode-runme#23]
Adding codelens in the default editor to run readme commands in the vscode terminal would be less disruptive than switching to the full blown notebooks.

**Comment by christian-bromann** [comment]
@pomdtr we shipped codelense support in Runme [`v1.2.0`](https://github.com/stateful/vscode-runme/releases/tag/1.2.0). Any feedback would be much appreciated.

@sourishkrout I suggest to close this issue. We don't have any documentation around codelense yet, I will raise a PR for it.

**Comment by christian-bromann** [comment]
Seems like we have it documented, added a little tweak to make it easier discoverable: https://github.com/stateful/docs.runme.dev/pull/208

**Comment by joseeantonior** [comment]
Hi, @pomdtr! It seems like this has been resolved and documented. If you encounter any issues please do let us know by opening an issue. Thanks for reporting it!
