### ISSUE TITLE
UX issues when updating name configuration for cell

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#247]
If I attempt to update the cell name through the VS Code UI, I loose focus on the input and some other weird things happen that make it almost impossible to properly enter the name:

![ux-bug](https://user-images.githubusercontent.com/731337/221754701-ccdb559d-9860-412d-ae2a-afa22b86537f.gif)

**Comment by sourishkrout** [comment]
The outputs are collapsed, so after repeatedly clicking on "Configure" it won't show the output. Clicking on the blue bar while uncollapse.

@degrammer can you check if there's a single key shortcut, just like `Y` and `M` which we fixed. That's getting in the way here?

**Comment by degrammer** [comment]
This is already fixed. Checked with @christian-bromann at last stable release.
