### ISSUE TITLE
CLI button won't pass subdirectory/filename

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#25]
If a markdown file is located in a subdirectory, the CLI button will launch `runme run` in the incorrect working directory.

**Comment by christian-bromann** [comment]
See #38

I am not sure what you mean with "wrong" in this context. I assume one would like to always go from the working space directory. The patch implements a new configuration for handling this.

**Comment by sourishkrout** [comment]
This issue is about the `CLI button` per cell. The problem is illustrated below. The command should have been executed at the path of the README and not the root of the repo.

![image](https://user-images.githubusercontent.com/250527/199018057-00be222d-3ffc-4877-9ab4-efffc9083358.png)
