### ISSUE TITLE
Remaining parity features for Runner

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#252]
- [x] Deep integrations: Vercel/deno (not priority)
- [x] Terminal dimensions (not priority)

**Comment by mxsdev** [comment]
This is now contingent on [runme/#168](https://github.com/stateful/runme/pull/168), which implements PTY sizing, and #267 , which fixes the deno/vercel integrations, but needs PTY sizing for the `deployctl` script to work with interactive mode.

PTY sizing currently uses 80 columns as a default so integration client-side is not strictly necessary, but would be nice anyways.
