### ISSUE TITLE
Investigate options for running Runme server per window vs per root process

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#255]
Would be good to take a look at how other language server VSCode integrations deal with this problem, so we can figure out next steps regarding this issue.

**Comment by mxsdev** [comment]
We will be proceeding with one process per window for now. We will take an incremental approach for port assignment for now.

**Comment by sourishkrout** [comment]
One side note, when we have some breathing room, we could consider looking into gRPC over stdio: https://github.com/grpc/grpc-node/issues/2038 - not super important. Just so we don't forget.
