### ISSUE TITLE
Update CLI provider to point to the shipped Runme CLI

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#288]
Currently we have a CLI button for every code block that is suppose to use the Runme CLI to execute the command inside:

![cli](https://user-images.githubusercontent.com/731337/224189757-28cf1108-4e08-4daf-8454-58a7b14c9246.gif)

The button is using the `CliProvider` class which checks whether the CLI is installed to run the action. Now that we have the CLI shipped as part of the extension we can just point directly to it.

@sourishkrout happy to take a stab at this if you think this make sense.

**Comment by sourishkrout** [comment]
This is about using the packaged binary's CLI versus looking inside the PATH (if installed via homebrew or other).

If so, please go ahead; I assume it's a subtle change.

Fyi, we will have to revisit the CLI button once the GRPC Runner integration wraps up. However, that's out of scope until we cross that bridge.
