### ISSUE TITLE
Duplicate cell execution error

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#289]
When running multiple cell executions, we display this unfriendly error message to the user:

<img width="533" alt="Screenshot 2023-03-10 at 10 26 20 AM" src="https://user-images.githubusercontent.com/4001529/224360124-00296f23-d97b-4695-a55b-2c09033fa00b.png">

- Figure out if there is a better way to handle this situation, it could be by disabling the configuration buttons if the cell is in an execution state or by exploring with [supportExecutionOrder](https://github.com/stateful/vscode-runme/blob/d2dfda7beb5259843cebf7cdedc20ffdd6226a08/src/extension/kernel.ts#L63)

Steps to reproduce the issue:
- Run a background task
- Click configure while running
- You should get the above error

**Comment by mxsdev** [comment]
Did some investigation. The only way I found in the VSCode API to modify a cell's outputs is through a running execution, and you are not allowed more than 1 running execution at a time. `supportsExecutionOrder` appears to be strictly aesthetic (showing the number in the bottom left corner).

So the only way I saw to fix this was to keep track of the running execution ourselves, and force all modifications of the output to be done in a unified way. 

I was able to implement this in #304
