### ISSUE TITLE
Run in mdx files

### ISSUE THREAD

**Issue by tylerbecks** [stateful/vscode-runme#30]
We use docusaurus and, thus, mdx files almost exclusively in our documentation site.  Is there a way to enable this extension for [`.mdx` files](https://docusaurus.io/docs/markdown-features/react)?

**Comment by sourishkrout** [comment]
hey @tylerbecks. Thank you for reporting this! We should be able to add Runme as default editor for `.mdx` files. Should be able to turn this around quickly. Stay tuned!

**Comment by sourishkrout** [comment]
Just to be clear @tylerbecks, the rendering of components inside of your markdown will likely not work out of the box. If that's something you want we should track it in a separate ticket.

**Comment by tylerbecks** [comment]
Yup I figured about the components. That would be awesome if we can use this in mdx. Btw I work at LinkedIn and just posted this in a few slack channels. We got some excitement from our temas.

**Comment by sourishkrout** [comment]
Tracking mdx support here: https://github.com/stateful/vscode-runme/issues/33

**Comment by sourishkrout** [comment]
Closing since the `.mdx` extension as of v0.2.15 will open Runme as well which was the scope of the original issue.
