### ISSUE TITLE
Publish/release workflow fails when OpenVSX publishing is turned on

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#31]
Unfortunately, this impacts tagging negatively. Let's restructure the pipeline to be fault-tolerant.

**Comment by christian-bromann** [comment]
Can this be closed with https://github.com/stateful/vscode-runme/commit/4503b52e4dbc20510cd10e77f04e7f3c01553283 ?

**Comment by sourishkrout** [comment]
> Can this be closed with [4503b52](https://github.com/stateful/vscode-runme/commit/4503b52e4dbc20510cd10e77f04e7f3c01553283) ?

Yes, I think so. I just need to wait until I got a chance to run the workflow to test the fix which happened late last night.

It's unclear if it actually will work since OpenVSX fixed the API endpoint and it now no longer keeps dangling.

Closing for now. Let's open a new ticket if we run into issues again.
