### ISSUE TITLE
Issues parsing ENV with multiple variable definitions

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#32]
- [x] Short-term fixed applied
- [ ] Add unit test coverage
- [ ] Potential refactor to simplify

Original issue:
![image](https://user-images.githubusercontent.com/250527/197621185-6d919823-2338-4ab7-bc4d-500579fe2466.png)

The ENV unpacking is incorrect for https://github.com/stateful/runme.dev#readme

**Comment by sourishkrout** [comment]
Commit above is just a bandaid.

**Comment by christian-bromann** [comment]
Please see https://github.com/stateful/vscode-runme/pull/37
