### ISSUE TITLE
Use better font family for integrated terminal

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#403]
## Current Behavior

Given my VS Code Runme configurations:

```
"runme.experiments.grpcRunner": true
"runme.terminal.interactive": true
"runme.terminal.nonInteractive": true
```

If I run a code cell in interactive or non-interactive mode the terminal font is not a monospace one:

<img width="668" alt="Screenshot 2023-04-11 at 13 22 19" src="https://user-images.githubusercontent.com/731337/231280612-e21c0b2b-ffbf-4ace-98c8-94a6b8518887.png">

## Desired Behavior

I am not sure the origin of this problem. If I set-up VS Code incorrectly, I would like to see better docs on how this can be configured better. If my configuration is not at fault I would love to see Runme using a better default font family.

**Comment by mxsdev** [comment]
Discussed this, turns out VSCode has a fallback mechanism when the font isn't installed on the system, which the notebook terminal does not have.

One solution is to use the `FontFaceSet` API

Bromann pointed out if this isn't fixed it should be noted in stateful/runme.dev#119

**Comment by joseeantonior** [comment]
I'm unable to reproduce this as of today. However, if it's still an issue, let's reopen.
