### ISSUE TITLE
UX Punchlist

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#430]
- [x] Reconsider showing notifications for Copy, Stop Task, etc - are those really noteworthy enough?
- [x] “Run with Runme” button in Explorer context menu
- [x] Add bundled binary’s path to extension’s [EnvironmentVariableCollection](https://code.visualstudio.com/api/references/vscode-api#EnvironmentVariableCollection) so that it’s included in the PATH
- Clean up Settings:
    - [x] Remove changing core defaults. Users should use markdown annotations instead, changing underlying core defaults individually will lead to non-determinism working on shared markdowns
    - [x] Port for Runme Server? Perhaps this should be “Endpoint Port” and only be a client connection setting in case server runs out-of -band
- [x] Consider adding an annotation to skip ENV VAR prompting

For later:

- [ ] Consider “x” button inside of each notebook UX outputs
- [ ] Show "exit" with error code on non-background tasks too

**Comment by mxsdev** [comment]
> Add bundled binary’s path to extension’s [EnvironmentVariableCollection](https://code.visualstudio.com/api/references/vscode-api#EnvironmentVariableCollection) so that it’s included in the PATH

According to my tests, VSCode prepends the shell $PATH to the integrated $PATH. What this means is that, while you can provide access to new executables through `EnvironmentVariableCollection`, you cannot override already provided commands. Unless there is something I'm overlooking here.

Similar issue occurs for spawning a new terminal.

@sourishkrout
