### ISSUE TITLE
[error] [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!

### ISSUE THREAD

**Issue by victor-heliomar** [stateful/vscode-runme#447]
## Explanation

I'm trying to open a markdown file in VSCode with runme extension and it never ends of load and never show the content of MD. I checked the output in console and got this message: `[error] [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!`

## Screenshots

![image](https://user-images.githubusercontent.com/66505715/234341288-416bc9d3-f53a-4a96-bbea-b190e7f82b54.png)

**Comment by mxsdev** [comment]
Hi! Thank you so much for reporting this issue.

If you could first of all let us know your Operating System & architecture, that would be very useful.

Second, there is an extension setting called "Enable Logger" - if you could turn that on, restart VSCode, and then re-send your logs, that could be extremely helpful for figuring out how to solve your issue.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/16108792/234347312-28559007-31d7-4f1e-ba2e-e490f2c6b1b0.png">

**Comment by victor-heliomar** [comment]
Hi! Thanks for the quick answer. Will check the logger on my side

About my operative system, I'm not sure if this Neofetch screenshot can help u

![image](https://user-images.githubusercontent.com/66505715/234409587-582cd089-bf98-43f2-8d4f-c6d50238e4d1.png)

Also here is my version of VSCode: visual-studio-code-bin 1.77.3-1

![image](https://user-images.githubusercontent.com/66505715/234409712-04a01f4b-17e7-42c2-b2d8-857bea61716f.png)

**Comment by victor-heliomar** [comment]
I think the logs didn't change after I enabled the Logger

![image](https://user-images.githubusercontent.com/66505715/234410747-3cd72c27-d983-4069-a2a7-ae9691a69411.png)

**Comment by mxsdev** [comment]
@victor-heliomar 

Looks like the logs actually go to the dev console (`Developer: Toggle Developer Tools` command to open), but not to the VSCode output! Let me know if they show up - if so, you can save the console logs by going to console, right clicking, and selecting "Save as..."

If you could also try [downloading the latest cli](https://github.com/stateful/runme/releases/tag/v1.0.2) and running `runme server --address localhost:7863 --dev`, the resulting console output could be useful here.

Thanks again, and sorry you're experiencing this!

**Comment by victor-heliomar** [comment]
Hi. Not prob. Thanks for helping with my problem

Here is my console log
<details>
<summary>console log</summary>
log.ts:421  INFO Electron sandbox mode is enabled!
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.vscode-selfhost-test-provider' wants API proposal 'testContinuousRun' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-vscode.remote-repositories' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'github.vscode-pull-request-github' wants API proposal 'contribEditorGutterMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:431  WARN Via 'product.json#extensionEnabledApiProposals' extension 'ms-toolsai.jupyter' wants API proposal 'notebookControllerKind' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:441   ERR Extension 'github.copilot-nightly' wants API proposal 'semanticSimilarity' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:441   ERR Extension 'github.copilot-nightly' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, interactive
product.json (WINS): inlineCompletionsAdditions
log.ts:421  INFO [GitHub.copilot-nightly]: Command `interactiveEditor.start` appears multiple times in the `commands` section.
console.ts:137 [Extension Host] [Runme] Activating Extension
console.ts:137 [Extension Host] [Runme] Server process #7819 started on port 7863
console.ts:137 [Extension Host] {"level":"info","ts":1682511904.725241,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511905.5217226,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #7819 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
console.ts:137 [Extension Host] [Runme] Server process #7852 started on port 7864
console.ts:137 [Extension Host] {"level":"info","ts":1682511905.53887,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

mainThreadExtensionService.ts:112 Activating extension 'GitHub.heygithub' failed: EISDIR: illegal operation on a directory, read.
$onExtensionActivationError @ mainThreadExtensionService.ts:112
log.ts:441   ERR [Extension Host] (node:7783) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:7783) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `exe --trace-deprecation ...` to show where the warning was created)
T @ console.ts:137
console.ts:137 [Extension Host] {"level":"info","ts":1682511906.6517518,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}
listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #7852 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
console.ts:137 [Extension Host] [Runme] Server process #8040 started on port 7865
console.ts:137 [Extension Host] {"level":"info","ts":1682511907.2775474,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511907.6784115,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}
listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #8040 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
console.ts:137 [Extension Host] [Runme] Server process #8119 started on port 7866
console.ts:137 [Extension Host] {"level":"info","ts":1682511907.7307272,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511909.2276385,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #8119 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
console.ts:137 [Extension Host] [Runme] Server process #8205 started on port 7867
console.ts:137 [Extension Host] {"level":"info","ts":1682511909.251401,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511910.9262307,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #8205 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9069 started on port 7868
console.ts:137 [Extension Host] {"level":"info","ts":1682511910.9488454,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511911.382678,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9069 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9513 started on port 7869
console.ts:137 [Extension Host] {"level":"info","ts":1682511911.406396,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511911.9556415,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9513 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9540 started on port 7870
console.ts:137 [Extension Host] {"level":"info","ts":1682511911.97854,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511913.2385807,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9540 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9630 started on port 7871
console.ts:137 [Extension Host] {"level":"info","ts":1682511913.2677457,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511916.5094092,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9630 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9709 started on port 7872
console.ts:137 [Extension Host] {"level":"info","ts":1682511916.5382686,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511917.466603,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9709 closed with code 1
log.ts:441   ERR [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
console.ts:137 [Extension Host] Failed to start runme server, retrying. Error: Server closed prematurely!
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] [Runme] Server process #9778 started on port 7873
console.ts:137 [Extension Host] {"level":"info","ts":1682511917.5134513,"caller":"tls/tls.go:99","msg":"generating new TLS certificate..."}

console.ts:137 [Extension Host] {"level":"info","ts":1682511918.564975,"caller":"tls/tls.go:179","msg":"successfully generated new TLS certificate!"}

console.ts:137 [Extension Host] listen tcp: lookup localhost on 192.168.1.1:53: no such host

console.ts:137 [Extension Host] [Runme] Server process #9778 closed with code 1
notificationsAlerts.ts:42 Failed to start Runme server. Reason: Cannot start server. Error: Server closed prematurely!
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
(anonymous) @ mainThreadMessageService.ts:77
d @ mainThreadMessageService.ts:42
$showMessage @ mainThreadMessageService.ts:36
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
event.ts:42 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onWillAddFirstListener @ event.ts:42
l.l @ event.ts:819
(anonymous) @ event.ts:118
onWillAddFirstListener @ event.ts:178
l.l @ event.ts:819
B @ listWidget.ts:621
F @ listWidget.ts:1430
Q @ listWidget.ts:1410
U @ listService.ts:249
j @ instantiationService.ts:119
createInstance @ instantiationService.ts:85
l @ notificationsList.ts:83
show @ notificationsList.ts:56
M @ notificationsToasts.ts:206
(anonymous) @ notificationsToasts.ts:153
execute @ dom.ts:163
dt @ dom.ts:203
viewLine.ts:418 monospace assumptions have been violated, therefore disabling monospace optimizations!
monospaceAssumptionsAreValid @ viewLine.ts:418
monospaceAssumptionsAreValid @ viewLine.ts:293
P @ viewLines.ts:587
(anonymous) @ viewLines.ts:154
h @ async.ts:891
g @ async.ts:886
setTimeout (async)
schedule @ async.ts:858
renderText @ viewLines.ts:655
I @ view.ts:406
(anonymous) @ view.ts:364
U @ view.ts:557
G @ view.ts:364
v @ view.ts:230
F @ view.ts:360
execute @ dom.ts:163
dt @ dom.ts:203
requestAnimationFrame (async)
e.scheduleAtNextAnimationFrame @ dom.ts:214
e.runAtThisOrScheduleAtNextAnimationFrame @ dom.ts:226
D @ view.ts:354
render @ view.ts:486
Qb @ codeEditorWidget.ts:1718
setModel @ codeEditorWidget.ts:507
setInput @ textFileEditor.ts:126
await in setInput (async)
M @ editorPanes.ts:422
D @ editorPanes.ts:252
openEditor @ editorPanes.ts:129
(anonymous) @ editorGroupView.ts:1075
zb @ editorGroupView.ts:1100
yb @ editorGroupView.ts:1057
openEditors @ editorGroupView.ts:1138
openEditors @ editorService.ts:602
await in openEditors (async)
Fb @ window.ts:1031
Db @ window.ts:979
await in Db (async)
(anonymous) @ window.ts:192
emit @ VM4 sandbox_bundle:124
onMessage @ VM4 sandbox_bundle:49
</details>

will try to run runme has you mentioned

**Comment by victor-heliomar** [comment]
This is the response of `runme server --address localhost:7863 --dev`
![image](https://user-images.githubusercontent.com/66505715/234586387-435cb5db-48c1-4bb5-987f-f14fa5f30f38.png)

**Comment by mxsdev** [comment]
Hm, that's strange. Seems that `localhost` isn't recognized on your system.

First question: do you have `localhost` defined in your hosts file? Normally you should have the following line in your `/etc/hosts` file, though you may have to add this manually on Arch:

```
127.0.0.1 localhost
```

Otherwise, are you using a VPN?

**Comment by victor-heliomar** [comment]
I have installed ExpressVPN, I usually use it, but in this moment where I'm testing runme, it's disabled.

hmm I don't have localhost defined in my hosts file
![image](https://user-images.githubusercontent.com/66505715/234685665-334fb8d4-4f46-42dd-9e29-d51b4d021e5f.png)

**Comment by victor-heliomar** [comment]
I added it to my /etc/hosts file. But I think I should restart my PC and test again. Will try at the end of the day to check if that helps with the problem

**Comment by victor-heliomar** [comment]
I added it to my `/etc/hosts` file. seems like now works when I run it from the file that I downloaded 
![image](https://user-images.githubusercontent.com/66505715/234686410-28f9dcfd-d00f-4b77-a286-bc937bab2726.png)

**Comment by victor-heliomar** [comment]
Hey! It worked now.

![image](https://user-images.githubusercontent.com/66505715/234686870-74a906a4-f753-40c8-8f80-532b0baf2814.png)

@mxsdev that was. Thanks a lot for the help!

**Comment by mxsdev** [comment]
Great! Closing for now, and I've opened #456 for preventing this issue from affecting others in the future.

Feel free to re-open if the issue re-occurs.
