### ISSUE TITLE
Configuration sometimes not openable before running first script

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#497]
Sometimes, clicking on configuration to open the annotation doesn't work until you've run at least one script.

Discovered by @admc

**Comment by sourishkrout** [comment]
> Sometimes, clicking on configuration to open the annotation doesn't work until you've run at least one script.
> 
> Discovered by @admc

Do you have any idea what's causing this? We used to have the issue that the notebook kernel wasn't ready and needed selection. However, I thought we caught that exception and prompted the user accordingly.

**Comment by mxsdev** [comment]
Can't say at the moment, I'd have to do some further investigation to be sure. 

Best guess is it has something to do with not being allowed to create a notebook execution?

**Comment by sourishkrout** [comment]
Makes sense. If it happens again, a screenshot or something would be helpful (cc @admc).

**Comment by sourishkrout** [comment]
I have a hunch that the multiple output refactor rejiggered the code so that the "kernel not selection" exception is no longer caught and handled @mxsdev. I'll try to repro it again later; however, I did see the exception in the logging console (unhandled).

**Comment by sourishkrout** [comment]
Have not seen this error crop up ever since we reshuffled some code. Please open again when you run up against it @mxsdev @admc.
