### ISSUE TITLE
Include `npm i` and `npm run watch` in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#498]
These two scripts are essential for our dev workflow, so why aren't they in our readme file?

cc @admc

**Comment by sourishkrout** [comment]
Install is right here: https://github.com/stateful/vscode-runme/blob/main/CONTRIBUTING.md?plain=1#L81

It's a bit crowded in this section which we could clean up. I suppose most folks run the default build task (at least, that's what I do SHIFT+CMD+B) for the watcher. However, we could make that more explicit.

**Comment by mxsdev** [comment]
> I suppose most folks run the default build task (at least, that's what I do SHIFT+CMD+B) for the watcher. However, we could make that more explicit.

On my pc and adam's, the default build task hangs on the watcher. I can make a separate issue for this if you want.

Still, it's probably good to give people options, in case they'd rather "own" the watcher.

**Comment by sourishkrout** [comment]
> > I suppose most folks run the default build task (at least, that's what I do SHIFT+CMD+B) for the watcher. However, we could make that more explicit.
> 
> On my pc and adam's, the default build task hangs on the watcher. I can make a separate issue for this.
> 
> Still, it's probably good to give people options, in case they'd rather "own" the watcher.

Do you have the recommended extensions installed? That's probably why.

I'll add both to the guidelines.

**Comment by sourishkrout** [comment]
Try again please @admc.
