### ISSUE TITLE
UX Improvement: Action button to `Open With` picker

### ISSUE THREAD

**Issue by lorenzejay** [stateful/vscode-runme#51]
editor opens .md with either built in text editor or runme view

**Comment by sourishkrout** [comment]
> Open with dropdown that shows options for the different types of terminal shells - e.g. open with
> 
> * bash
> * shell
> * etc..

not sure what you mean... have a screenshot?

**Comment by lorenzejay** [comment]
@sourishkrout  actually looking for clarification from your UX proposal. Can you clarify, what you meant by
"Action button to open “Open With…” picker"

**Comment by sourishkrout** [comment]
> @sourishkrout actually looking for clarification from your UX proposal. Can you clarify, what you meant by "Action button to open “Open With…” picker"

Buttons in the screenshot below. There's a SetContext/GetContext API which can be used to make them show conditionally.

![image](https://user-images.githubusercontent.com/250527/201753606-00083265-5d41-4e27-b3a3-e510ef05dbdb.png)

**Comment by lorenzejay** [comment]
gotcha. Will work on this next

**Comment by sourishkrout** [comment]
> gotcha. Will work on this next

here are some reference docs: https://code.visualstudio.com/api/references/when-clause-contexts

**Comment by lorenzejay** [comment]
@sourishkrout this is what you're looking for right

![openwith-editor-menu](https://user-images.githubusercontent.com/63378463/201793751-afc7e629-ed72-475a-8067-d716c21ff731.gif)

**Comment by sourishkrout** [comment]
> @sourishkrout this is what you're looking for right
> 
> ![openwith-editor-menu](https://user-images.githubusercontent.com/63378463/201793751-afc7e629-ed72-475a-8067-d716c21ff731.gif) [ ![openwith-editor-menu](https://user-images.githubusercontent.com/63378463/201793751-afc7e629-ed72-475a-8067-d716c21ff731.gif) ](https://user-images.githubusercontent.com/63378463/201793751-afc7e629-ed72-475a-8067-d716c21ff731.gif) [ ](https://user-images.githubusercontent.com/63378463/201793751-afc7e629-ed72-475a-8067-d716c21ff731.gif)

Yep! Yo got it. ideally we could have the `play` button when it's non-runme and other one to switch to text and/or preview.

**Comment by lorenzejay** [comment]
@sourishkrout 

notice new icon when opening runme notebook to text-editor .md file

![openwith-editor-menu-v2](https://user-images.githubusercontent.com/63378463/201970518-7f1000a2-cf97-438c-a95c-669d8800684b.gif)

**Comment by lorenzejay** [comment]
light theme too

<img width="1413" alt="Screen Shot 2022-11-15 at 8 17 41 AM" src="https://user-images.githubusercontent.com/63378463/201970925-09442abe-fef9-4cb3-a067-08c8dd1458d8.png">
<img width="697" alt="Screen Shot 2022-11-15 at 8 17 48 AM" src="https://user-images.githubusercontent.com/63378463/201970929-9d815edb-a707-4f72-a4bf-2a42d0609472.png">

**Comment by christian-bromann** [comment]
Closing as #58 got merged.
