### ISSUE TITLE
GitHub Action Renderer: Render most recent Workflow Runs

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#515]

**Comment by degrammer** [comment]
Depends on https://github.com/stateful/vscode-runme/pull/514 to be merged

**Comment by christian-bromann** [comment]
@degrammer can you provide a description for this issue? What do you think needs to get done?

**Comment by joseeantonior** [comment]
@degrammer Please provide a description for this issue, including actual results vs. expected results. Otherwise will close and we can reopen if needed.

**Comment by joseeantonior** [comment]
I'll go ahead and close this since we don't have a description.
