### ISSUE TITLE
Revert to sharp corners in annotations slideout

### ISSUE THREAD

**Issue by mxsdev** [stateful/vscode-runme#562]
I personally feel as though we should go back to sharp corners on the configuration window, so as to be consistent with the surrounding UI.

cc @degrammer 

<img width="592" alt="image" src="https://github.com/stateful/vscode-runme/assets/16108792/6c8515c2-0bcf-4e47-8433-23d73880d3da">

**Comment by degrammer** [comment]
Fixed at https://github.com/stateful/vscode-runme/pull/563
