### ISSUE TITLE
Cell config typo

### ISSUE THREAD

**Issue by admc** [stateful/vscode-runme#584]
Should be "output".

<img width="491" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/8a53a7d1-60e0-4ec4-b36c-259e77b959e4">

**Comment by Testingsux1** [comment]
Boys im glade all yall having fun beating this thing to death but github is monatering mu phone now so keep up the good work and as for the cams thanks guys you like that loop your watching lol

**Comment by christian-bromann** [comment]
Fixed by https://github.com/stateful/vscode-runme/pull/588
