### ISSUE TITLE
Display category run button having unsaved document

### ISSUE THREAD

**Issue by duvanmonsa** [stateful/vscode-runme#591]
When adding a new category for a document we need to make sure we display the Run by Category button even if the document has not been saved just yet.

**Comment by christian-bromann** [comment]
@duvanmonsa I am not sure how the Runme binary is suppose to pick up the category without having the user save the document first. There are sure ways to dynamically tell Runme that the user is about to add a new category but that seems to be very impractical. Can you further explain the use case why it would be valuable to the user to run by category without having the change stored to the cell?

**Comment by duvanmonsa** [comment]
@christian-bromann Well I was not sure if it was possible maybe you are right and it makes no sense. it was weird to see you add a new Category but then it won't show you the option to run the cells for that category, if you feel saving the document is required that makes sense to me and we can close the ticket :)

**Comment by sourishkrout** [comment]
Is it a matter of saving or reloading? If it's the former than a confirmation notification reminding the user to save to apply the change after adding a category is an imperfect but honest solution.

**Comment by christian-bromann** [comment]
> Is it a matter of saving or reloading? If it's the former than a confirmation notification reminding the user to save to apply the change after adding a category is an imperfect but honest solution.

Yes, it is the former. I could see two approaches here:

- show a notification as soon as anything was changed
- show a notification when something in the cell configuration was changed and the window got closed, e.g. by clicking on `Configure` again

What do you think?

**Comment by sourishkrout** [comment]
> 

Don't we know when a category was added? Only then.

**Comment by christian-bromann** [comment]
> Only then.

To clarify: a user adds a category through the Notebook UI, we will have a notification popping up, reminding the user to save the document for the changes to have an impact. The popup will have a save button that on click will save the document. If the user presses `CMD`+`s` the pop-up disappears.

**Comment by sourishkrout** [comment]
That sounds right. Not sure if the VS Code API lets you clear notifications (left to users exclusively) on, let's say `CMD+S`. However, even if not, that's a nice to have.

**Comment by christian-bromann** [comment]
How about this:

![savewarn](https://github.com/stateful/vscode-runme/assets/731337/8ce72976-2bc0-4590-868d-d94cbe4db252)
