### ISSUE TITLE
Markdown complete checkmark behavior

### ISSUE THREAD

**Issue by admc** [stateful/vscode-runme#596]
When adding markdown, then code, then markdown, then code, sometimes the "complete" checkmark to save the markdown shows up on what looks like "mouse out" and sometimes when the focus changed (which requires a click, or many). I'm wondering if we should explore using "mouseout", or even adding a `cmd+enter` keyboard shortcut to save it without a click.

Either way it should be consistent.

You can see what I mean here: https://runme.dev/examples/hello-world.gif

**Comment by sourishkrout** [comment]
The way this works is part of the VS Code Notebook APIs. If it's broken we should file a ticket against https://github.com/microsoft/vscode. For the keyboard shortcuts, both `shft+enter` (alternative is ESC) and `option+enter` (insert empty cell after currrent) will do what the requested `cmd+enter` does.
