### ISSUE TITLE
Open/Close Terminal Cell Button

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#61]
Currently users have the ability to open the terminal if they were running interactive cells, e.g.:

![Screenshot 2022-11-16 at 11 32 22](https://user-images.githubusercontent.com/731337/202276506-8419052f-707f-4196-8b36-4ae77467c290.png)

To complete the experience it would be great if we could change the button to say "Close Terminal". Unfortunately VS Code doesn't re-render that section quite often so there is no way for use to do that atm.

**Comment by christian-bromann** [comment]
> I'll give this a shot

Feel free, it would be great to better understand when VS Code re-renders these provider. I initially tried to tackle this myself and gave up as I believe it is currently not possible.

**Comment by lorenzejay** [comment]
@christian-bromann have you tried this ?
<img width="1655" alt="Screenshot 2022-11-22 at 10 46 03 AM" src="https://user-images.githubusercontent.com/63378463/203396285-178ca8a6-d4f4-4ff9-b069-3c5bf9f08d9e.png">

would recall `provideCellStatusBarItems` and can use an if statement to show open/close right?

**Comment by lorenzejay** [comment]
> @christian-bromann have you tried this ? <img alt="Screenshot 2022-11-22 at 10 46 03 AM" width="1655" src="https://user-images.githubusercontent.com/63378463/203396285-178ca8a6-d4f4-4ff9-b069-3c5bf9f08d9e.png">
> 
> would recall `provideCellStatusBarItems` and can use an if statement to show open/close right?

nvm... this doesnt work as the provider is not calling the command which won't tell if there was any event

**Comment by mxsdev** [comment]
I was able to get some partial progress on this problem! In particular, I was able to figure out how to accomplish re-rendering, using `onDidChangeCellStatusBarItems`. This allows for the following:

<img src="https://user-images.githubusercontent.com/16108792/212572392-de5c375b-f73d-4a71-970e-83a7aa0805e1.gif" />

Unfortunately, there is no way (as far as I know) to determine if the bottom panel is open, so the best you can do is tell if the relevant terminal is "active." Still, this provides a solution to #124 (see #125), and could be of use for other future features.

**Comment by christian-bromann** [comment]
@sourishkrout I think we can close this issue as we don't have the button anymore. The way the UX suggests running task within the CLI doesn't raise a need for this functionality.

**Comment by sourishkrout** [comment]
Agreed.
