### ISSUE TITLE
Runme terminal settings

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#611]
Runme Terminal, should allow more customization, so far we support Font family and Font size, and there are a bunch of terminal settings that can be provided like:

- Scrollback: Amount of retained rows when lines are scrolled beyond the initial viewport
- Fast scroll sensitivity: The scroll speed multiplier used for fast scrolling
-  Cursor style
- Cursor width
Review what other settings can be supported

**Comment by sourishkrout** [comment]
In progress here: https://github.com/stateful/vscode-runme/pull/798
