### ISSUE TITLE
Issue with guesslang

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#64]
Does not seem to work as expected (please fill in details @adambabik) for https://github.com/micro/micro/blob/41203a045376fa15aa4ac29cedf69e6f2634a39e/README.md

Proposal for fix: https://github.com/stateful/vscode-runme/issues/54#issuecomment-1317059139

Let's get a better description, screenshot, or something from a user's perspective (what's broken?) before we apply the patch and call it fixed.

**Comment by adambabik** [comment]
Funny thing is that I cannot reproduce that error. I reseted repos to their original state and I don't get it anymore. However, there is a different problem - invalid prediction for entries like:

```
go install github.com/micro/micro/v3@latest
```

and 

```
docker pull ghcr.io/micro/micro:latest
```

They have no language detected and are rendered as markdown:

![Screenshot 2022-11-17 at 11 56 51](https://user-images.githubusercontent.com/277870/202429323-770c91e5-1ef9-459f-860b-6c01301f8470.png)

The other day, they were rendered as code blocks without any manual annotation - I checked that. `runme json` returns it as a code block but with the empty `executable` field.

**Comment by adambabik** [comment]
> The other day, they were rendered as code blocks without any manual annotation - I checked that. `runme json` returns it as a code block but with the empty `executable` field.

I checked it and if `executable` is empty or unsupported then in the VS Code we rewrite it to be a markdown block. Shouldn't we stay with the code block and allow a user to change it manually by clicking on the language name?

![Screenshot 2022-11-17 at 12 35 04](https://user-images.githubusercontent.com/277870/202435998-1b1e6748-0419-4015-a9f2-402ef337b49c.png)

**Comment by sourishkrout** [comment]
Fixed the zero-len array bug and while I was at it improved the guesslang weighting to bias towards executable langs if the pstdev within the top3 is <1%. Seems to work well for majority of edge cases but not all.

https://github.com/stateful/vscode-runme/commit/4d6c523aa20d40f051686aebb0b4dcf4b228e8ac
