### ISSUE TITLE
Https cloning repository from link

### ISSUE THREAD

**Issue by RadFromOrange** [stateful/vscode-runme#644]
hi, nice Extension!
Could you add support for HTTPS cloning from link vscode:stateful.runme... ? It only support git@ ssh for now?

**Comment by sourishkrout** [comment]
Hey, there @RadFromOrange! Thanks for the request.

Luckily we already support HTTPS repo references besides SSH-based ones. I've added a blurb to the docs which you can find here please: https://docs.runme.dev/features#run-with-runme-deep-linking.

Essentially you can use either SSH or HTTPS notations for the repository parameter. In the above's example just replace git@github.com:stateful/blog-examples.git with https://github.com/stateful/blog-examples respectively.

Thank you for using Runme and please consider joining Runme's discord where other users and the team usually congregate: https://discord.gg/runme

**Comment by RadFromOrange** [comment]
thanx ,i was missing the ending .git
