### ISSUE TITLE
Outfit the repo to be OSS / contributor friendly

### ISSUE THREAD

**Issue by admc** [stateful/vscode-runme#69]
- contributing
- code of conduct
- development.md
- clean up readme

**Comment by sourishkrout** [comment]
Let's put an emphasis on informing users of Runme. Contributors are not unimportant but the project is too early to spend a lot of time there.

**Comment by admc** [comment]
"Let's put an emphasis on informing users of Runme" what does that mean?

**Comment by christian-bromann** [comment]
> * contributing

Anything we want to do differently from our existing [`Contributing.md`](https://github.com/stateful/vscode-runme/blob/main/CONTRIBUTING.md)?

> * code of conduct

We have a [default CoC](https://github.com/stateful/.github/blob/main/CODE_OF_CONDUCT.md) document that automatically applies to org repos. We can have an individual CoC if we want to differ from that one.

> * development.md

Is currently part of `CONTRIBUTING.md`, I personally would not see a need for a separated file as our dev setup is very trival atm unless you have other specific content you like to put in there.

> * clean up readme

Anything in particular to clean up?

**Comment by joseeantonior** [comment]
Seems like this has been addressed. We don't have a `development.md` file but the `contributing.md` file does contain the necessary information. Closing this for now but can reopen if needed.
