### ISSUE TITLE
[Enhance]  Add support for online video and local video playback, making the extension's functions and functions more extensive and powerful.

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#702]
Very, very good `markdown` editing extension!

After using it for a while, I found that the `markdown` editing experience is really great!
But there is a problem that has been unable to solve? It has been unable to play online videos and local videos in `markdown` files in the `VSCode` environment.

After using the excellent `markdown` editing extension provided by you, I look forward to adding support for online video and local video playback, so that the functions and functions of this extension will be more extensive and powerful. With the rapid development of media industries such as `YouTube` in recent years, almost all `markdown` editors so far support streaming media playback functions such as online videos and local videos. Only `VSCode` does not support streaming media playback functions such as online video and local video, which is very frustrating. Hope you can implement this feature further.

Thank you so much for such an excellent `markdown` editing extension! 👍😜

OS: Windows10
Version: VScode 1.81
Version: 1.9.1691170218

**Comment by zhouxinghong** [comment]
![image](https://github.com/stateful/vscode-runme/assets/54253524/77b1e312-90a7-4957-96e3-d72ada8b581d)

![image](https://github.com/stateful/vscode-runme/assets/54253524/509bcbaf-ec45-4c86-99d7-04ceded8af04)

**Comment by zhouxinghong** [comment]
```
<video controls muted preload="auto" poster="https://cdn.ly.com/oBw8dOUV.jpg" src="F:\video\79be16f6b3177b45c-1920-1080.mp4"> 
</video>
`

**Comment by zhouxinghong** [comment]
![image](https://github.com/stateful/vscode-runme/assets/54253524/553f0aef-5626-43d4-b56f-5e9b8ac3be60)
Hello! Playing a video file has no audio and cannot maximize the video
Video information: `.mp4` based on `H264`

**Comment by zhouxinghong** [comment]
Windows10
Latest version 1.9.1691779450

**Comment by zhouxinghong** [comment]
Hello! Sometimes this version loads into the video, sometimes it doesn't.
Windows10
Latest version 1.9.1691779450

**Comment by christian-bromann** [comment]
@zhouxinghong thanks for raising the issue.

Currently Runme has not much control about how videos are rendered in VS Code. However, there might be still ways we can improve the behavior. Let me bring this to the team and get back to you.

**Comment by zhouxinghong** [comment]
Thank you very much! 😜👏
Replenish:
Video information cannot be rendered if the <Video> tag attribute wraps, like this:
![image](https://github.com/stateful/vscode-runme/assets/54253524/f9a5cf61-2a4d-4e5e-964a-057ed24bef7a)

```html
<video controls muted preload="auto" 
poster="https://cdn.u.com/image/iAgMxQog.jpg" src="https://bb.amm.en.ga/video/ga001.mp4"> 
</video>
```

**Comment by zhouxinghong** [comment]
@christian-bromann Great development team:
Hello! Can this video playback function be implemented in the next version?

**Comment by zhouxinghong** [comment]
> @zhouxinghong thanks for raising the issue.
> 
> Currently Runme has not much control about how videos are rendered in VS Code. However, there might be still ways we can improve the behavior. Let me bring this to the team and get back to you.

👍👍👍👍👍

**Comment by zhouxinghong** [comment]
Hello! Can you give priority to implementing this video playback function? We've been looking forward to it for a long time. . .

> Currently Runme has not much control about how videos are rendered in VS Code. However, there might be still ways we can improve the behavior. Let me bring this to the team and get back to you.

Hello! Can you give priority to implementing this video playback function? We've been looking forward to it for a long time. . .😂
