### ISSUE TITLE
[Improved] Suggestions for further improvement of UI appearance

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#720]
[Improved] The button's foreground color, background color, border color, and mouse hover background color are inconsistent with the theme button's foreground color, background color, border color, and mouse hover background color

Hello friends!
The button's foreground color, background color, border color, and mouse hover background color should automatically adapt to the theme button's foreground color, background color, border color, and mouse hover background color.

Supplementary note:
The shape of the button should be consistent with VSCode, and it will be more beautiful to unify the rounded corners.

After this improvement, the user experience will be very friendly!
Looking forward to your further improvements to this appearance feature. Thank you so much for your hard work! 👍😜

OS: Windows10
Version: VScode 1.81
Version: 1.9.1690302206
![image](https://github.com/stateful/vscode-runme/assets/54253524/862b9cce-5764-42c1-a6f7-f9a8e22a04c7)
![image](https://github.com/stateful/vscode-runme/assets/54253524/44b0b12b-ad42-455a-9966-574888dd720b)
![image](https://github.com/stateful/vscode-runme/assets/54253524/133c6055-6050-40a7-a76f-e6edc335bc76)
![image](https://github.com/stateful/vscode-runme/assets/54253524/0dd3c5bb-e04d-485a-9c3a-c83bbdb97f48)
![image](https://github.com/stateful/vscode-runme/assets/54253524/4a077e2b-e31b-4f67-9ba4-c20a661b9e72)
![image](https://github.com/stateful/vscode-runme/assets/54253524/dd039b3c-3fce-4abe-be0c-1bc179d7dda1)

Supplementary note:
The shape of the button should be consistent with `VSCode`, and it will be more beautiful to unify the rounded corners.

OS: Windows10
Version: VScode 1.81
Version: 1.9.1690302206

**Comment by christian-bromann** [comment]
@zhouxinghong thanks for raising the issue.

I will look how we can enable the color theme for the following icon:
![image](https://github.com/stateful/vscode-runme/assets/54253524/862b9cce-5764-42c1-a6f7-f9a8e22a04c7)

I am not sure if it possible for us without bringing this to the VS Code team to update the theme for the other UI elements given that these are built-in components of VS Code and we as extension developer have not much capabilities to modify them.

**Comment by admc** [comment]
@christian-bromann i wonder if there's a way to setup the svgs for dark and light to inherit fill and or stroke from the css variables. Maybe we can look at how other extensions do it. I'm pretty sure I got this working properly with marquee.

**Comment by christian-bromann** [comment]
Yes, looking into this as we speak 😉

**Comment by christian-bromann** [comment]
I looked into this and unfortunately it is currently not possible to embed any CSS variables into the SVG icon due the fact that it is loaded as an `background-image` and therefore has no access to the CSS variables. For it to work the SVG needs to be embedded into the DOM tree. I raised an issue in the VS Code project: https://github.com/microsoft/vscode/issues/189201 to ask for more flexibility.

**Comment by zhouxinghong** [comment]
There are already many excellent extensions in the community that can automatically adapt to all appearance elements of the theme.

**Comment by christian-bromann** [comment]
@zhouxinghong can you mention some?

**Comment by zhouxinghong** [comment]
I can't remember which extension it was 😂

**Comment by zhouxinghong** [comment]
@christian-bromann But you can contact @mjbvz this friend, he should be able to help you solve this problem, at least give you a valid solution, because I submitted a similar problem to him before, and he solved it very well.

**Comment by christian-bromann** [comment]
I've raised an issue in the VS Code project, let's see what they say: https://github.com/microsoft/vscode/issues/189201

**Comment by zhouxinghong** [comment]
Um! Seeking official support is great! 👍😜

**Comment by zhouxinghong** [comment]
![](https://user-images.githubusercontent.com/54253524/256126657-4a077e2b-e31b-4f67-9ba4-c20a661b9e72.png)
Copy button background color, foreground color, border color do not match theme button background color, foreground color, border color.

Version | 1.9.1691170218

**Comment by christian-bromann** [comment]
> Copy button, configure button, CLI button, HTML button mouse hover background color, foreground color, border color do not match theme button background color, foreground color, border color. . .

Unfortunately these colors are not set by Runme and are part of the theming and embedded into VS Code. There is not much we can do to fix this.

**Comment by zhouxinghong** [comment]
Thank you very much! 😜👏

**Comment by zhouxinghong** [comment]
![image](https://github.com/stateful/vscode-runme/assets/54253524/53d153bf-9606-4d05-965f-8f4910cf8a03)
The border of this icon can be thicker, so that it will have the same effect as the border style of other icons👍

**Comment by admc** [comment]
On it!

**Comment by admc** [comment]
I did a revision of the button, which is in the pre-release runme extension if you want to check it out:

<img width="173" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/03893ed2-0e77-410c-bf50-9dd50a30bce4">

**Comment by zhouxinghong** [comment]
> I did a revision of the button, which is in the pre-release runme extension if you want to check it out:
> 
> <img alt="image" width="173" src="https://user-images.githubusercontent.com/5144/275592529-03893ed2-0e77-410c-bf50-9dd50a30bce4.png">

Very cool! 👍
In addition, can you please implement the following requirements😜, I am very much looking forward to these functions:
https://github.com/stateful/vscode-runme/issues/702
https://github.com/stateful/vscode-runme/issues/767

**Comment by zhouxinghong** [comment]
![image](https://github.com/stateful/vscode-runme/assets/54253524/508ba458-4135-4c31-a481-6a965c0ce705)
1. The dark theme does not display icons;
2. The icon border color will not automatically adapt to the theme color;

**Comment by admc** [comment]
Interesting, I need to spend some more time on this because it's all working on my setup. Which themes are you using?

**Comment by zhouxinghong** [comment]
All dark themes integrated with VSCode
VSCode 1.83
Windows 10

**Comment by zhouxinghong** [comment]
Very cool! 👍
In addition, can you please implement the following requirements😜, I am very much looking forward to these functions:
https://github.com/stateful/vscode-runme/issues/702
https://github.com/stateful/vscode-runme/issues/767

**Comment by zhouxinghong** [comment]
1. This version of the icon cannot automatically adapt to the theme color.
Version | 1.11.1697580585

2. This version of the icon can automatically adapt to the theme color, but the border width of the icon needs to be improved.
![image](https://github.com/stateful/vscode-runme/assets/54253524/53d153bf-9606-4d05-965f-8f4910cf8a03)
The border of this icon can be thicker, so that it will have the same effect as the border style of other icons👍3
