### ISSUE TITLE
[Feature request] Copying webpage content and pasting it into a Markdown editor cannot retain the source format of webpage content, such as hyperlinks, emoticons, emoticons, bold, italic, underline, image resources, video resources, etc. The original format and style of webpage content.

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#721]
Hello friends!
Copying webpage content and pasting it into a `Markdown` editor cannot retain the source format of webpage content, such as hyperlinks, emoticons, emoticons, bold, italic, underline, image resources, video resources, etc. The original format and style of webpage content.

Because so far, choosing VSCode to edit `Markdown` files has been unable to preserve the original formatting and style of content copied from web pages. This question is very disturbing. Looking forward to your further implementation of this feature. Thank you so much for all your hard work! 👍😜

OS: Windows10
Version: VScode 1.81
Version: 1.9.1691170218

**Comment by zhouxinghong** [comment]
The reason why this function is requested is that when you rely on network content for `Markdown` document editing, then it is very useful at this time, and so far the `VSCode` extension center cannot find an extension with similar functions. If the `vscode-runme` extension can add this feature, it will be a boon for users who often rely on web content for `Markdown` document editing. 😜

**Comment by christian-bromann** [comment]
@zhouxinghong thanks for raising the issue.

Unfortunately Runme (in this context) is "only" a VS Code extension and the feature you are requesting is currently out of scope for us. It should be ideally be implemented as part of VS Code or as an individual extension.

**Comment by zhouxinghong** [comment]
OK! Thank you very much for your reply!
I raised this issue with VSCode but they said that this functionality should be implemented by an extension...
Although this function is beyond the scope of your current work, considering that it can make runme have a better user experience, I still hope that you and your excellent team can seriously consider developing this function as a sister extension with runme . Because all professional Markdown editing tools have this function, and runme is the best Markdown editing tool in the VSCode community. If the runme user experience is getting better and better and the functions are getting more and more perfect, it will also be very helpful for runme to accumulate more users. Although other professional Markdown editing tools have this function, they are always commercial software. Therefore, as the functions of runme become more and more perfect, I believe that most of them should choose to use runme in VSCode to edit work and study documents like me. 😜
