### ISSUE TITLE
[Feature request] Allow users to modify the content layout, font size, and margin size of `Markdown` files to be compatible with `Markdown` file content reading and printing.

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#722]
[Feature request] Allow users to modify the content layout, font size, and margin size of `Markdown` files to be compatible with `Markdown` file content reading and printing.

By using the found reading `Markdown` content in the `Runme runs Markdown` extension, you will find that the content typesetting, font, and margin of the entire `Markdown` file will be very large and the content typesetting, font, and margin of the standard `Markdown` file It is completely different, so in order to consider the content typesetting and printing of the `Markdown` file, it is recommended to add a setting item to allow the user to reduce the content typesetting, font size, and margin size of the `Markdown` file to the standard `Markdown` file content size. Typesetting to be compatible with `Markdown` file content reading and printing.

Please see the comparison pictures below:
![2023-07-26_1441028888888888888888888888888](https://github.com/stateful/vscode-runme/assets/54253524/8054b464-a3e2-4c9a-b3db-1210f499f901)

![2023-07-26_99999999999999999999999999999999999](https://github.com/stateful/vscode-runme/assets/54253524/eec81189-c754-41de-ba1d-03460342a3fd)

Looking forward to your further implementation of this feature. Thank you so much for your hard work! 👍😜
After implementing these functions, the user experience will be very friendly!

OS: Windows10
Version: VScode 1.81
Version: 1.9.1690302206

**Comment by sourishkrout** [comment]
Did you intentionally close this issue after opening it @zhouxinghong?

**Comment by zhouxinghong** [comment]
terribly sorry! 😊 The truth is not what you think! Because I am worried that you have been assigned too many questions, I will temporarily close it. If you have time and think this idea is very good and willing to implement this function, then I will open this question to you at any time, waiting for you to implement it it.

**Comment by sourishkrout** [comment]
> terribly sorry! 😊 The truth is not what you think! Because I am worried that you have been assigned too many questions, I will temporarily close it. If you have time and think this idea is very good and willing to implement this function, then I will open this question to you at any time, waiting for you to implement it it.

No need to be worried. Please feel free to ask. We can't always promise to respond with a fix but we will definitely let you know.

**Comment by zhouxinghong** [comment]
Now that the problem is already being dealt with correctly, let's wait for the release of the next version of VSCode to see how the improvement works?

**Comment by zhouxinghong** [comment]
If the improved results are not as good as you would like, then this report is still something to consider.

**Comment by zhouxinghong** [comment]
Hello! Has this issue been fixed?

**Comment by christian-bromann** [comment]
Unfortunately the VS Code team has reverted the change. See more here: https://github.com/microsoft/vscode/pull/188335. I will re-open and try to re-submit the change.

**Comment by christian-bromann** [comment]
Raised a new PR https://github.com/microsoft/vscode/pull/190291
