### ISSUE TITLE
```py not working with "Run Block" inline

### ISSUE THREAD

**Issue by admc** [stateful/vscode-runme#723]
Not sure if this is a known issue, but logging just incase.

When I run the python example in "Non-Shell Languages" in the notebook, it executes as expected, but when I click "Run Block" it fails.

<img width="1624" alt="image" src="https://github.com/stateful/vscode-runme/assets/5144/fed39592-1ba1-4f7e-9346-3d89956e9a23">

**Comment by sourishkrout** [comment]
Good catch. Shipping a new pre-release with a fix as we speak.
