### ISSUE TITLE
Multiple categories aren't support within the notebook

### ISSUE THREAD

**Issue by christian-bromann** [stateful/vscode-runme#733]
Based on the [docs](https://docs.runme.dev/configuration#run-all-cells-by-category) a user can define multiple categories for a cell. However in VS Code the extension merges the categories together:

<img width="759" alt="Screenshot 2023-07-28 at 15 24 54" src="https://github.com/stateful/vscode-runme/assets/731337/78eb42e6-211e-4b08-bb64-f7f0c8c20847">

**Comment by sourishkrout** [comment]
I really don't love that logic like this needs reimplementation per client.
