### ISSUE TITLE
E2E test to render initial workflow view in GitHub Actions integration

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#748]
A breaking changes introduced in Octokit floated under the radar.

Fix is here: https://github.com/stateful/vscode-runme/pull/747

**Comment by sourishkrout** [comment]
When there's time, let's see if we can get a simple test case, please @christian-bromann.

**Comment by christian-bromann** [comment]
@sourishkrout just letting you know that adding an e2e test for this seems to be more difficult that it seems. For the GitHub integration to work we need to authenticate with GitHub during the session. Unfortunately it is not possible to just switch to Chrome like a real user. I am currently looking into adding a custom `TestAuthenticationProvider` that can do this for us without switching apps through environment variables.
