### ISSUE TITLE
Bug: Readme.md will not close or save preventing VSCode from exiting

### ISSUE THREAD

**Issue by mdstaff** [stateful/vscode-runme#76]
VSCode metadata:

Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No

Screenshot of errors:
![Screen Shot 2022-12-06 at 4 25 51 PM](https://user-images.githubusercontent.com/244685/206026487-ed463745-c492-4878-afdb-fdc7ef79b7ef.png)

Example Git Repo with Readme.md file: TODO

Detailed Description: TODO

Expected Behaviour:
- Readme.md closes with click on file with X
- Readme.md closes with close file keyboard shortcut ( Option + W on Mac )
- VSCode closes and restarts ( several scenarios )

**Comment by sourishkrout** [comment]
Thanks for the bug report @mdstaff! Any chance you could share the `README.md` either here or (if sensitive content is involved) out of band via email sebastian(at)stateful.com?

**Comment by sourishkrout** [comment]
The resolution of this issue is blocked by shipping "notebook editing" which is currently in the works (highest priority). Will verify and resolve this issue once editing landed.

**Comment by mdstaff** [comment]
👋 Hi @sourishkrout I think opening this issue was premature.  I later learned this issue happened due to the extension being in "read-only" mode and I had accidentally modified the file.  Happy to close this if that is expected behaviour due to the lack of edit permissions.

**Comment by sourishkrout** [comment]
> 👋 Hi @sourishkrout I think opening this issue was premature. I later learned this issue happened due to the extension being in "read-only" mode and I had accidentally modified the file. Happy to close this if that is expected behaviour due to the lack of edit permissions.
> 
> I was able to "discard changes" and then close the file with the GUI (the little x next to the tab) or the keyboard shortcut.

All good, @mdstaff! While the read-only mode is a known limitation, we might add a footnote to people know about this scenario. However, we're actually really close and very excited to make writing (full editing) available and move past read-only. Hopefully as early as next week!

Let's keep the ticket open as we are working through this. Really appreciate you taking the time to file the ticket, @mdstaff.

**Comment by sourishkrout** [comment]
Hi @mdstaff, starting with v0.4 (current stable) this issue should be fixed. Please note that you will still receive a warning if the underlying README.md/markdown file is not version-tracked in git. Let us know if you have questions!
