### ISSUE TITLE
Supports running cells and code in preview mode to prevent data and code tampering

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#767]
Supports running cells and code in preview mode to prevent data and code tampering

Greetings! After using it for some time, I realized that since there is no read mode at the moment, many times, accidental misuse can lead to user determined data and code being changed or lost again. So considering this situation, reading mode needs to be added. To prevent user misuse.

Notice:
This feature is equivalent to the reading mode of other professional `Markdown` editors.

Windows10
Latest version 2.1.xx.xxx

**Comment by zhouxinghong** [comment]
If the extension adds a reading mode, it can completely replace the default Markdown view of VSCode.

**Comment by christian-bromann** [comment]
Thanks for raising the issue @zhouxinghong 

Let me take this to the team and get back to you.

**Comment by zhouxinghong** [comment]
Thank you very much! 😜👏

**Comment by zhouxinghong** [comment]
> Thanks for raising the issue @zhouxinghong
> 
> Let me take this to the team and get back to you.

Hello! Can you give priority to implementing this reading mode function? We've been looking forward to it for a long time. . . 😂

**Comment by zhouxinghong** [comment]
Since there is no reading mode and accidentally touching the keyboard or mouse after opening the file, the user's edited and determined data content will be inadvertently changed or deleted again. This problem is very frustrating 😒

**Comment by zhouxinghong** [comment]
@christian-bromann 
@joseeantonior
Hello! May I ask which version you plan to add the reading mode function to?
I think this feature is very important and useful, and I hope to see it in the next version. Thank you very much for providing an excellent document editing extension. 😜

**Comment by zhouxinghong** [comment]
> Hello, @zhouxinghong - thanks for reaching out and providing your feedback.
> 
> We have this item listed in our backlog. However, we are currently working in other priorities and are unable to provide you with an estimate time of arrival. We are have released other awesome features, such as shebang support. Please note that this issue will be updated to reflect the status of the item once it's resolved, but like I mentioned, we are unable to provide an estimate at this time.

OK! Thank you very much! We look forward to the early arrival of this feature. 👍😜

**Comment by zhouxinghong** [comment]
Since there is no reading mode and accidentally touching the keyboard or mouse after opening the file, the user's edited and determined data content and code will be inadvertently changed or deleted again. This problem is very frustrating 😒

**Comment by joseeantonior** [comment]
Thank you for your feedback. We'll consider it for the future. We are not currently planning on this in our roadmap, so I will go ahead and close this issue.
