### ISSUE TITLE
Hello! Left and right edit scrolling is out of sync.

### ISSUE THREAD

**Issue by zhouxinghong** [stateful/vscode-runme#768]
Hello! Left and right edit scrolling is out of sync.
Hello! Left and right edit scrolling is out of sync. Hope you can fix this in the next version. Thank you very much!
Windows10
runme latest version
![image](https://github.com/stateful/vscode-runme/assets/54253524/71bacb4a-c5aa-4359-9d32-62935cb877d9)
Runme Markdown left and right editing scrolling cannot be synchronized

https://github.com/stateful/vscode-runme/assets/54253524/36369486-b7b1-466f-a142-267d86fb0745

VSCode Markdown left and right editing scroll synchronization

https://github.com/stateful/vscode-runme/assets/54253524/f93041b9-cb5b-4812-b39a-890dbc5a5217

**Comment by christian-bromann** [comment]
Hey @zhouxinghong , thanks for raising the issue.

Unfortunately Runme has no control over this feature. This should be reported within [VS Code](https://github.com/microsoft/vscode) instead. Let me know if you have further questions.

**Comment by zhouxinghong** [comment]
I understand!
Thank you very much! 😜👏
