### ISSUE TITLE
promptEnv=false is asking me to set env variables

### ISSUE THREAD

**Issue by ruzickap** [stateful/vscode-runme#778]
Hello guys.

I tried to run this simple example in VS Code and it is still asking me to set Environment Variables even when I use `promptEnv=false`:

<pre>
```sh { promptEnv=false }
export AWS_DEFULT_REGION="eu-central-1"
echo "${AWS_DEFULT_REGION}"
```
</pre>

<img width="1098" alt="image" src="https://github.com/stateful/vscode-runme/assets/1434387/bc25a135-d5d7-4e98-b678-70f071cfc37b">

I would like to set the environment variables without user interaction (because if there are many of them - then this is a real issue)

Thank you for looking at it...

**Comment by christian-bromann** [comment]
Hey @ruzickap , thanks for reporting! I raised a PR and we will get this fixed with the next edge release.
