### ISSUE TITLE
TypeScript example provides no usable errors when ts-node is not installed

### ISSUE THREAD

**Issue by PavelSafronov** [stateful/vscode-runme#804]
I tried to run the TypeScript example in [stateful/vscode-runme/blob/main/examples/README.md](https://github.com/stateful/vscode-runme/blob/main/examples/README.md?plain=1#L60-L63) in VS Code, but without having `ts-node` installed. The example failed to run and did not give any usable errors:
<img width="1604" alt="image" src="https://github.com/stateful/vscode-runme/assets/1359724/24c1c343-65c1-4de7-b0ca-59b4d1c51e63">
There's a pop-up that suggests changing the interpreter field in the "Configure" foldout, but it's not clear how this field should be configured. And, I suspect, changing the interpreter will not fix the true issue: `ts-node` isn't installed.

Clicking the "CLI" button on the example leads to a slightly better experience, in that I get an error, but it is not clear what's causing the error:
<img width="1604" alt="image" src="https://github.com/stateful/vscode-runme/assets/1359724/fda4fb99-5b09-4360-9c28-62c9b64a41f5">

After installing `ts-node` (which I only realized was necessary after seeing [this issue](https://github.com/stateful/runme/issues/351)), the errors go away and the example works.

**Comment by christian-bromann** [comment]
Thanks for reporting @PavelSafronov , we will try to provide a fix as soon as possible.

**Comment by sourishkrout** [comment]
@PavelSafronov, sorry this one took so long. Please take a look at the [linked PR](https://github.com/stateful/vscode-runme/pull/997) for a better error message for cases where the interpreter couldn't be auto-detected.
