### ISSUE TITLE
Stuck in VSCode -> Browser -> VSCode infinite loop

### ISSUE THREAD

**Issue by nickdos** [stateful/vscode-runme#868]
I've just installed Runme in VSCode (Mac OS - arm64) and when I click the left toolbar "Runme" icon I see a panel that tells me to "Get Started". I click this button and it takes me to https://app.runme.dev/getting-started that simply shows me a video and a button labelled "Install Runme for VS Code". No other options apart from seeing my GH icon in top-right, showing I'm logged-in. So, I click this (again) and it takes me back to VSCode and the loop continues. I can't seem to do anything to break me out of this infinite loop. 

I've tried uninstalling and re-installing (from within VSCode) but I get the same loop.

After reading the docs like a caveman I see I should've been prompted to clone the example repo but I never saw that and the plugin seems to be in an intermediate state, not having done this, as a guess. 

Just a small thing, I run a default dark mode, which is pretty common and the text in the plugin is almost unreadable, being black text. None of the other plugins I use have an issue with dark mode, just saying.

![image](https://github.com/stateful/vscode-runme/assets/532845/9eb673bf-6ad6-4831-a21f-af066ca07044)

**Comment by admc** [comment]
Thanks so much for reporting this @nickdos, you're totally right -- that empty state is not very helpful!

I've just made some improvements and they should now be live. Can you check it out and let me know your thoughts?

<img width="504" alt="Screenshot 2023-10-02 at 23 22 10" src="https://github.com/stateful/vscode-runme/assets/5144/8fb3f37b-84c5-4854-ada3-993b4d1b5f57">

<img width="531" alt="Screenshot 2023-10-02 at 23 21 44" src="https://github.com/stateful/vscode-runme/assets/5144/de5da53a-d985-4f8b-b19b-7a1d3c349553">

**Comment by nickdos** [comment]
Thanks @admc - that is a huge improvement. I'm now up and running and attempting to convert a bash script into a quasi integration test suite.
