### ISSUE TITLE
"New File" menu entry

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#91]
Lets add a "New File" menu entry as per https://github.com/microsoft/vscode-github-issue-notebooks/blob/5ea44157dbd076dc6066540df431a17ca54010a8/package.json#L108-L113

_Originally posted by @sourishkrout in https://github.com/stateful/vscode-runme/issues/46#issuecomment-1320205889_

**Comment by christian-bromann** [comment]
Moved into "Done" as referenced PR got merged.
