### ISSUE TITLE
Polish for v0.4 authoring release

### ISSUE THREAD

**Issue by sourishkrout** [stateful/vscode-runme#92]
- [x] Bring back "CLI" button: https://github.com/stateful/runme/issues/83
- [x] Fix unsupported languages UX (currently show no-effect ▶️ button)
- [ ] Consider Action buttons to switch between Runme<>MD to open in-place vs side-by-side
- [x] Finalize #91 
- [x] Revert https://github.com/stateful/vscode-runme/commit/2b31a79eb3e4a3f4e9004b518dfba6d77a5ff409 pending Runme stable release
- [x] Edit "known limitations" in marketplace readme
- [x] Public v1.0 roadmap on `stateful/runme/projects`
- [x] Copy edits all around
- [x] Announcement

**Comment by christian-bromann** [comment]
> * Bring back "CLI" button: [Code block name in metadata runme#83](https://github.com/stateful/runme/issues/83)

See https://github.com/stateful/vscode-runme/pull/96

**Comment by sourishkrout** [comment]
Shipped as https://github.com/stateful/vscode-runme/releases/tag/0.4.0
