### ISSUE TITLE
Always display execution time configuration option

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#920]
Got the following feedback from a user:

> Hello All. A quick question: I love the duration (time-taken) displayed at bottom left of Code block. However, when the execution completes, this duration goes away. Is there anyway to retain last run duration. This is helpful to understand how long each command is taking to run. I am using RunMe with VSCode.

Figure out if we can always display the execution time and make it configurable at cell level

**Comment by sourishkrout** [comment]
I think this is done, no @degrammer & @joseeantonior? This doesn't need a config option; very non-controversial to have the execution duration be visible at all times.


![Image](https://github.com/stateful/vscode-runme/assets/250527/2e4467a9-133e-4175-b501-b827e8d82b43)

**Comment by joseeantonior** [comment]
imo this is pretty straightforward and useful. If you're good to close I'm good as well.

**Comment by sourishkrout** [comment]
> imo this is pretty straightforward and useful. If you're good to close I'm good as well.

let's see if @degrammer has anything he'd like to clarify. otherwise let's close.

PS: Start-, end-time, as well as exec duration is also available in Runme cloud now, too.
