### ISSUE TITLE
unblock having latest version of vscode-uri

### ISSUE THREAD

**Issue by degrammer** [stateful/vscode-runme#923]
The last version of vscode-uri is breaking wdio-vscode-service, read more at https://github.com/stateful/vscode-runme/pull/922
Review a potential fix so we can have the last version, once fixed, remove it from the excluded deps in dependabot.yml

**Comment by joseeantonior** [comment]
@degrammer It seems like this was fixed on #922 - could you please confirm so we can close this issue?
